### ISSUE TITLE
Pre-launch checklist

### ISSUE THREAD

**Issue by danielgamage** [oakstudios/joinmastodon#29]
- [ ] double check that the github integration is working properly once we merge our fork. (https://github.com/oakstudios/joinmastodon/pull/28#discussion_r923623413)
- [ ] get translations before launching to production
  - [ ] get arabic translations (#31)
- [x] remove [typecheck build ignore](https://github.com/oakstudios/joinmastodon/blob/093ef5b42c49bb55d0b8be9febb9482f74435658/next.config.js#L6-L8) from `next.config.js`

**Comment by danielgamage** [comment]
are we keeping the `z_archive/` dir in for further translation work?

**Comment by mikabusante** [comment]
i ran the recover script earlier and i think we have all the existing strings! so i think we're good to delete the archive

**Comment by danielgamage** [comment]
moving this to the fork PR
